/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalendarAgendaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// agenda-utils.ts
function filterAgendaEventsFromCalendar(events) {
  const normalized = events.map((event) => {
    const summary = cleanAgendaSummary(event.summary || event.title || "Untitled");
    const availability = getAgendaAvailability(event, summary);
    const start = event.start || null;
    const end = event.end || event.start || null;
    const startMs = start ? new Date(start).getTime() : NaN;
    const endMs = end ? new Date(end).getTime() : startMs;
    return {
      summary,
      start,
      end,
      location: event.location,
      allDay: !!event.allDay,
      availability,
      _startMs: startMs,
      _endMs: endMs
    };
  });
  const filtered = normalized.filter((event) => !["free", "tentative"].includes(event.availability));
  const meetingTimes = new Set(
    filtered.filter((event) => event.summary.trim().toLowerCase() === "meeting").map((event) => `${event._startMs}-${event._endMs}`)
  );
  return filtered.filter((event) => !(event.availability === "busy" && meetingTimes.has(`${event._startMs}-${event._endMs}`))).sort((a, b) => a._startMs - b._startMs).map(({ _startMs, _endMs, availability, ...rest }) => rest);
}
function getAgendaAvailability(event, summary) {
  if (event.availability)
    return String(event.availability).toLowerCase();
  if (event.transparency) {
    const transparency = String(event.transparency).toLowerCase();
    if (transparency === "transparent")
      return "free";
    if (transparency === "opaque")
      return "busy";
  }
  const text = `${summary || ""} ${event.description || ""}`;
  const match = text.match(/\b(Free|Busy|Tentative)\b/i);
  return match ? match[1].toLowerCase() : "busy";
}
function cleanAgendaSummary(text) {
  return String(text || "Untitled").replace(/\(\s*(Free|Busy|Tentative)\s*\)/gi, "").replace(/\b(Free|Busy|Tentative)\b/gi, "").replace(/\s{2,}/g, " ").replace(/^[-–—]\s*/, "").trim() || "Untitled";
}
function buildAgendaMarkdown(events) {
  const lines = ["## Agenda", ""];
  events.forEach((event) => {
    var _a;
    let timeLabel = "";
    if (event.allDay) {
      timeLabel = "All day";
    } else if (event.start) {
      const startDate = new Date(event.start);
      timeLabel = startDate.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
    }
    const summaryText = ((_a = event.summary) == null ? void 0 : _a.trim().toLowerCase()) === "meeting" ? "#work" : event.summary || "Untitled";
    let line = `- **${timeLabel}** ${summaryText}`;
    if (event.location) {
      line += ` _(${event.location})_`;
    }
    lines.push(line);
  });
  lines.push("");
  return lines.join("\n");
}

// main.ts
var DEFAULT_SETTINGS = {
  googleClientId: "",
  googleApiKey: "",
  accessToken: "",
  tokenExpiry: 0
};
var CalendarAgendaPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "insert-agenda-google",
      name: "Insert today's agenda from Google Calendar",
      editorCallback: async (editor, view) => {
        await this.fetchAndInsertAgenda(editor);
      }
    });
    this.addSettingTab(new CalendarAgendaSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Check if Google is authenticated
   */
  isAuthenticated() {
    return !!(this.settings.accessToken && this.settings.tokenExpiry > Date.now());
  }
  /**
   * Authenticate with Google using OAuth 2.0 implicit flow
   */
  async authenticateGoogle() {
    if (!this.settings.googleClientId) {
      new import_obsidian.Notice("Please configure Google Client ID in settings");
      return;
    }
    const redirectUri = "https://localhost";
    const scope = "https://www.googleapis.com/auth/calendar.readonly";
    const state = Math.random().toString(36).substring(7);
    const authUrl = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(this.settings.googleClientId)}&redirect_uri=${encodeURIComponent(redirectUri)}&response_type=token&scope=${encodeURIComponent(scope)}&state=${state}`;
    new import_obsidian.Notice("Opening Google authentication...");
    window.open(authUrl, "_blank");
    new import_obsidian.Notice("After authorizing, paste the access token from the URL into settings");
  }
  /**
   * Fetch events from Google Calendar and insert agenda
   */
  async fetchAndInsertAgenda(editor) {
    var _a;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please authenticate with Google Calendar first");
      await this.authenticateGoogle();
      return;
    }
    try {
      new import_obsidian.Notice("Fetching calendar events...");
      const today = new Date();
      const start = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 0, 0, 0, 0);
      const end = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 59, 59, 999);
      const response = await (0, import_obsidian.requestUrl)({
        url: `https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${start.toISOString()}&timeMax=${end.toISOString()}&singleEvents=true&orderBy=startTime`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.settings.accessToken}`,
          "Accept": "application/json"
        }
      });
      if (response.status !== 200) {
        throw new Error(`Failed to fetch events: ${response.status}`);
      }
      const data = response.json;
      const events = (data.items || []).map((event) => ({
        summary: event.summary || "Untitled",
        start: event.start.dateTime || event.start.date,
        end: event.end.dateTime || event.end.date,
        location: event.location,
        allDay: !event.start.dateTime,
        transparency: event.transparency
      }));
      this.insertAgenda(editor, events);
    } catch (error) {
      console.error("Failed to fetch calendar events:", error);
      if ((_a = error.message) == null ? void 0 : _a.includes("401")) {
        new import_obsidian.Notice("Authentication expired. Please re-authenticate in settings.");
        this.settings.accessToken = "";
        this.settings.tokenExpiry = 0;
        await this.saveSettings();
      } else {
        new import_obsidian.Notice("Failed to fetch calendar events. Check console for details.");
      }
    }
  }
  /**
   * Insert agenda at cursor position (read-only display)
   */
  insertAgenda(editor, events) {
    const agendaEvents = filterAgendaEventsFromCalendar(events);
    if (agendaEvents.length === 0) {
      new import_obsidian.Notice("No events to display");
      return;
    }
    const agendaText = buildAgendaMarkdown(agendaEvents);
    editor.replaceSelection(agendaText);
    new import_obsidian.Notice(`Displayed ${agendaEvents.length} event(s)`);
  }
};
var CalendarAgendaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calendar Agenda Settings" });
    containerEl.createEl("p", {
      text: "To use Google Calendar, you need to set up OAuth credentials:"
    });
    const steps = containerEl.createEl("ol");
    steps.createEl("li", { text: "Go to Google Cloud Console" });
    steps.createEl("li", { text: "Create a project and enable Google Calendar API" });
    steps.createEl("li", { text: "Create OAuth 2.0 credentials (Web application)" });
    steps.createEl("li", { text: "Add https://localhost as authorized redirect URI" });
    steps.createEl("li", { text: "Copy Client ID below" });
    new import_obsidian.Setting(containerEl).setName("Google Client ID").setDesc("OAuth 2.0 Client ID from Google Cloud Console").addText((text) => text.setPlaceholder("Enter your client ID").setValue(this.plugin.settings.googleClientId).onChange(async (value) => {
      this.plugin.settings.googleClientId = value;
      await this.plugin.saveSettings();
    }));
    const authStatus = containerEl.createDiv();
    authStatus.addClass("setting-item-description");
    if (this.plugin.isAuthenticated()) {
      authStatus.setText("\u2713 Authenticated with Google Calendar");
      authStatus.style.color = "green";
    } else {
      authStatus.setText("\u2717 Not authenticated");
      authStatus.style.color = "red";
    }
    new import_obsidian.Setting(containerEl).setName("Authenticate").setDesc("Sign in with Google Calendar").addButton((button) => button.setButtonText("Authenticate with Google").onClick(async () => {
      await this.plugin.authenticateGoogle();
    }));
    new import_obsidian.Setting(containerEl).setName("Access Token (from OAuth redirect)").setDesc("After authenticating, paste the access_token from the redirect URL").addText((text) => {
      text.setPlaceholder("Paste access token here").setValue("").onChange(async (value) => {
        if (value && value.length > 20) {
          this.plugin.settings.accessToken = value;
          this.plugin.settings.tokenExpiry = Date.now() + 3600 * 1e3;
          await this.plugin.saveSettings();
          new import_obsidian.Notice("Access token saved!");
          this.display();
        }
      });
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Clear authentication").setDesc("Remove stored access token").addButton((button) => button.setButtonText("Clear").setWarning().onClick(async () => {
      this.plugin.settings.accessToken = "";
      this.plugin.settings.tokenExpiry = 0;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Authentication cleared");
      this.display();
    }));
  }
};
