/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalendarAgendaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// agenda-utils.ts
function filterAgendaEventsFromCalendar(events) {
  const normalized = events.map((event) => {
    const summary = cleanAgendaSummary(event.summary || event.title || "Untitled");
    const availability = getAgendaAvailability(event, summary);
    const start = event.start || null;
    const end = event.end || event.start || null;
    const startMs = start ? new Date(start).getTime() : NaN;
    const endMs = end ? new Date(end).getTime() : startMs;
    return {
      summary,
      start,
      end,
      location: event.location,
      allDay: !!event.allDay,
      availability,
      _startMs: startMs,
      _endMs: endMs
    };
  });
  const filtered = normalized.filter((event) => !["free", "tentative"].includes(event.availability));
  const meetingTimes = new Set(
    filtered.filter((event) => event.summary.trim().toLowerCase() === "meeting").map((event) => `${event._startMs}-${event._endMs}`)
  );
  return filtered.filter((event) => !(event.availability === "busy" && meetingTimes.has(`${event._startMs}-${event._endMs}`))).sort((a, b) => a._startMs - b._startMs).map(({ _startMs, _endMs, availability, ...rest }) => rest);
}
function getAgendaAvailability(event, summary) {
  if (event.availability)
    return String(event.availability).toLowerCase();
  if (event.transparency) {
    const transparency = String(event.transparency).toLowerCase();
    if (transparency === "transparent")
      return "free";
    if (transparency === "opaque")
      return "busy";
  }
  const text = `${summary || ""} ${event.description || ""}`;
  const match = text.match(/\b(Free|Busy|Tentative)\b/i);
  return match ? match[1].toLowerCase() : "busy";
}
function cleanAgendaSummary(text) {
  return String(text || "Untitled").replace(/\(\s*(Free|Busy|Tentative)\s*\)/gi, "").replace(/\b(Free|Busy|Tentative)\b/gi, "").replace(/\s{2,}/g, " ").replace(/^[-–—]\s*/, "").trim() || "Untitled";
}
function buildAgendaMarkdown(events) {
  const lines = ["## Agenda", ""];
  events.forEach((event) => {
    var _a;
    let timeLabel = "";
    if (event.allDay) {
      timeLabel = "All day";
    } else if (event.start) {
      const startDate = new Date(event.start);
      timeLabel = startDate.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
    }
    const summaryText = ((_a = event.summary) == null ? void 0 : _a.trim().toLowerCase()) === "meeting" ? "#work" : event.summary || "Untitled";
    let line = `- **${timeLabel}** ${summaryText}`;
    if (event.location) {
      line += ` _(${event.location})_`;
    }
    lines.push(line);
  });
  lines.push("");
  return lines.join("\n");
}

// main.ts
var http = __toESM(require("http"));
var DEFAULT_SETTINGS = {
  googleClientId: "",
  googleClientSecret: "",
  refreshToken: "",
  accessToken: "",
  tokenExpiry: 0
};
var OAUTH_PORT = 42813;
var REDIRECT_URI = `http://localhost:${OAUTH_PORT}/callback`;
var OAUTH_SCOPE = "https://www.googleapis.com/auth/calendar.readonly";
var CalendarAgendaPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.oauthServer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "insert-agenda-google",
      name: "Insert today's agenda from Google Calendar",
      editorCallback: async (editor, view) => {
        await this.fetchAndInsertAgenda(editor);
      }
    });
    this.addSettingTab(new CalendarAgendaSettingTab(this.app, this));
  }
  async onunload() {
    if (this.oauthServer) {
      this.oauthServer.close();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Check if Google is authenticated
   */
  isAuthenticated() {
    return !!(this.settings.accessToken && this.settings.tokenExpiry > Date.now() || this.settings.refreshToken);
  }
  /**
   * Refresh access token using refresh token
   */
  async refreshAccessToken() {
    if (!this.settings.refreshToken) {
      return false;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: "https://oauth2.googleapis.com/token",
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: new URLSearchParams({
          client_id: this.settings.googleClientId,
          client_secret: this.settings.googleClientSecret,
          refresh_token: this.settings.refreshToken,
          grant_type: "refresh_token"
        }).toString()
      });
      if (response.status === 200) {
        const data = response.json;
        this.settings.accessToken = data.access_token;
        this.settings.tokenExpiry = Date.now() + data.expires_in * 1e3;
        await this.saveSettings();
        return true;
      }
    } catch (error) {
      console.error("Failed to refresh access token:", error);
    }
    return false;
  }
  /**
   * Start local OAuth server and authenticate with Google
   */
  async authenticateGoogle() {
    if (!this.settings.googleClientId || !this.settings.googleClientSecret) {
      new import_obsidian.Notice("Please configure Google Client ID and Secret in settings");
      return;
    }
    const state = Math.random().toString(36).substring(7);
    const authUrl = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(this.settings.googleClientId)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&response_type=code&scope=${encodeURIComponent(OAUTH_SCOPE)}&access_type=offline&prompt=consent&state=${state}`;
    new import_obsidian.Notice("Starting OAuth server...");
    return new Promise((resolve, reject) => {
      this.oauthServer = http.createServer(async (req, res) => {
        var _a, _b, _c, _d;
        try {
          const url = new URL(req.url || "", `http://localhost:${OAUTH_PORT}`);
          if (url.pathname === "/callback") {
            const code = url.searchParams.get("code");
            const returnedState = url.searchParams.get("state");
            if (!code) {
              res.writeHead(400, { "Content-Type": "text/html" });
              res.end("<html><body><h1>Error: No authorization code received</h1></body></html>");
              (_a = this.oauthServer) == null ? void 0 : _a.close();
              reject(new Error("No authorization code"));
              return;
            }
            if (returnedState !== state) {
              res.writeHead(400, { "Content-Type": "text/html" });
              res.end("<html><body><h1>Error: Invalid state (CSRF protection)</h1></body></html>");
              (_b = this.oauthServer) == null ? void 0 : _b.close();
              reject(new Error("Invalid state"));
              return;
            }
            try {
              const tokenResponse = await (0, import_obsidian.requestUrl)({
                url: "https://oauth2.googleapis.com/token",
                method: "POST",
                headers: {
                  "Content-Type": "application/x-www-form-urlencoded"
                },
                body: new URLSearchParams({
                  client_id: this.settings.googleClientId,
                  client_secret: this.settings.googleClientSecret,
                  code,
                  grant_type: "authorization_code",
                  redirect_uri: REDIRECT_URI
                }).toString()
              });
              if (tokenResponse.status === 200) {
                const data = tokenResponse.json;
                this.settings.accessToken = data.access_token;
                this.settings.refreshToken = data.refresh_token || this.settings.refreshToken;
                this.settings.tokenExpiry = Date.now() + data.expires_in * 1e3;
                await this.saveSettings();
                res.writeHead(200, { "Content-Type": "text/html" });
                res.end("<html><body><h1>\u2713 Authentication successful!</h1><p>You can close this window and return to Obsidian.</p></body></html>");
                new import_obsidian.Notice("\u2713 Google Calendar authenticated successfully!");
                setTimeout(() => {
                  var _a2;
                  (_a2 = this.oauthServer) == null ? void 0 : _a2.close();
                  this.oauthServer = null;
                }, 1e3);
                resolve();
              } else {
                throw new Error("Failed to exchange code for tokens");
              }
            } catch (error) {
              console.error("Token exchange error:", error);
              res.writeHead(500, { "Content-Type": "text/html" });
              res.end("<html><body><h1>Error: Failed to exchange authorization code</h1></body></html>");
              (_c = this.oauthServer) == null ? void 0 : _c.close();
              reject(error);
            }
          } else {
            res.writeHead(404, { "Content-Type": "text/plain" });
            res.end("Not found");
          }
        } catch (error) {
          console.error("OAuth server error:", error);
          res.writeHead(500, { "Content-Type": "text/plain" });
          res.end("Internal server error");
          (_d = this.oauthServer) == null ? void 0 : _d.close();
          reject(error);
        }
      });
      this.oauthServer.listen(OAUTH_PORT, () => {
        new import_obsidian.Notice(`OAuth server listening on port ${OAUTH_PORT}`);
        window.open(authUrl, "_blank");
      });
      this.oauthServer.on("error", (error) => {
        new import_obsidian.Notice("Failed to start OAuth server. Port may be in use.");
        console.error("Server error:", error);
        reject(error);
      });
    });
  }
  /**
   * Fetch events from Google Calendar and insert agenda
   */
  async fetchAndInsertAgenda(editor) {
    var _a;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please authenticate with Google Calendar first");
      await this.authenticateGoogle();
      return;
    }
    if (this.settings.tokenExpiry <= Date.now() && this.settings.refreshToken) {
      new import_obsidian.Notice("Refreshing access token...");
      const refreshed = await this.refreshAccessToken();
      if (!refreshed) {
        new import_obsidian.Notice("Failed to refresh token. Please re-authenticate.");
        await this.authenticateGoogle();
        return;
      }
    }
    try {
      new import_obsidian.Notice("Fetching calendar events...");
      const today = new Date();
      const start = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 0, 0, 0, 0);
      const end = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 59, 59, 999);
      const response = await (0, import_obsidian.requestUrl)({
        url: `https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${start.toISOString()}&timeMax=${end.toISOString()}&singleEvents=true&orderBy=startTime`,
        method: "GET",
        headers: {
          "Authorization": `Bearer ${this.settings.accessToken}`,
          "Accept": "application/json"
        }
      });
      if (response.status !== 200) {
        throw new Error(`Failed to fetch events: ${response.status}`);
      }
      const data = response.json;
      const events = (data.items || []).map((event) => ({
        summary: event.summary || "Untitled",
        start: event.start.dateTime || event.start.date,
        end: event.end.dateTime || event.end.date,
        location: event.location,
        allDay: !event.start.dateTime,
        transparency: event.transparency
      }));
      this.insertAgenda(editor, events);
    } catch (error) {
      console.error("Failed to fetch calendar events:", error);
      if ((_a = error.message) == null ? void 0 : _a.includes("401")) {
        new import_obsidian.Notice("Authentication expired. Refreshing...");
        const refreshed = await this.refreshAccessToken();
        if (refreshed) {
          return this.fetchAndInsertAgenda(editor);
        } else {
          new import_obsidian.Notice("Please re-authenticate in settings.");
        }
      } else {
        new import_obsidian.Notice("Failed to fetch calendar events. Check console for details.");
      }
    }
  }
  /**
   * Insert agenda at cursor position (read-only display)
   */
  insertAgenda(editor, events) {
    const agendaEvents = filterAgendaEventsFromCalendar(events);
    if (agendaEvents.length === 0) {
      new import_obsidian.Notice("No events to display");
      return;
    }
    const agendaText = buildAgendaMarkdown(agendaEvents);
    editor.replaceSelection(agendaText);
    new import_obsidian.Notice(`Displayed ${agendaEvents.length} event(s)`);
  }
};
var CalendarAgendaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calendar Agenda Settings" });
    containerEl.createEl("p", {
      text: "To use Google Calendar, you need to set up OAuth credentials:"
    });
    const steps = containerEl.createEl("ol");
    steps.createEl("li", { text: "Go to Google Cloud Console" });
    steps.createEl("li", { text: "Create a project and enable Google Calendar API" });
    steps.createEl("li", { text: "Create OAuth 2.0 credentials (Desktop app or Web application)" });
    steps.createEl("li", { text: `Add http://localhost:${OAUTH_PORT}/callback as authorized redirect URI` });
    steps.createEl("li", { text: "Copy Client ID and Client Secret below" });
    new import_obsidian.Setting(containerEl).setName("Google Client ID").setDesc("OAuth 2.0 Client ID from Google Cloud Console").addText((text) => text.setPlaceholder("Enter your client ID").setValue(this.plugin.settings.googleClientId).onChange(async (value) => {
      this.plugin.settings.googleClientId = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Google Client Secret").setDesc("OAuth 2.0 Client Secret from Google Cloud Console").addText((text) => {
      text.setPlaceholder("Enter your client secret").setValue(this.plugin.settings.googleClientSecret).onChange(async (value) => {
        this.plugin.settings.googleClientSecret = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    const authStatus = containerEl.createDiv();
    authStatus.addClass("setting-item-description");
    if (this.plugin.isAuthenticated()) {
      authStatus.setText("\u2713 Authenticated with Google Calendar");
      authStatus.style.color = "var(--text-success)";
    } else {
      authStatus.setText("\u2717 Not authenticated");
      authStatus.style.color = "var(--text-error)";
    }
    new import_obsidian.Setting(containerEl).setName("Authenticate").setDesc("Sign in with Google Calendar. This will open a browser window.").addButton((button) => button.setButtonText("Authenticate with Google").setCta().onClick(async () => {
      try {
        await this.plugin.authenticateGoogle();
        this.display();
      } catch (error) {
        new import_obsidian.Notice("Authentication failed. Check console for details.");
        console.error("Auth error:", error);
      }
    }));
    if (this.plugin.isAuthenticated()) {
      new import_obsidian.Setting(containerEl).setName("Clear authentication").setDesc("Remove stored tokens and sign out").addButton((button) => button.setButtonText("Sign Out").setWarning().onClick(async () => {
        this.plugin.settings.accessToken = "";
        this.plugin.settings.refreshToken = "";
        this.plugin.settings.tokenExpiry = 0;
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Signed out successfully");
        this.display();
      }));
    }
  }
};
